class ChecklistTask {
  final String id;
  final String title;
  final String description;
  final String category; // 'medical' | 'bienetre' | 'pratique'

  const ChecklistTask({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
  });
}

class PregnancyChecklistRepository {
  PregnancyChecklistRepository._();

  static List<ChecklistTask> forWeek(int week) {
    final clamped = week.clamp(1, 42);
    return _data[clamped] ?? _data[_nearest(clamped)]!;
  }

  static int _nearest(int week) => _data.keys
      .reduce((a, b) => (a - week).abs() < (b - week).abs() ? a : b);

  static const Map<int, List<ChecklistTask>> _data = {
    1: [
      ChecklistTask(id:'1-1', category:'medical',
        title:'Commencer les vitamines prénatales',
        description:'Prends 400 µg d\'acide folique chaque jour pour protéger le développement du système nerveux de ton bébé.'),
      ChecklistTask(id:'1-2', category:'bienetre',
        title:'Arrêter l\'alcool et le tabac',
        description:'Ces deux substances augmentent les risques de complications. Tu peux y arriver — demande du soutien si besoin.'),
      ChecklistTask(id:'1-3', category:'bienetre',
        title:'Réduire la caféine',
        description:'Limite à moins de 200 mg par jour, soit environ une tasse de café.'),
    ],
    4: [
      ChecklistTask(id:'4-1', category:'medical',
        title:'Faire un test de grossesse',
        description:'L\'hCG est détectable dès maintenant. Utilise les premières urines du matin pour plus de fiabilité.'),
      ChecklistTask(id:'4-2', category:'medical',
        title:'Prendre le premier rendez-vous prénatal',
        description:'La plupart des médecins programment la première consultation entre les semaines 8 et 10.'),
      ChecklistTask(id:'4-3', category:'medical',
        title:'Continuer les vitamines prénatales',
        description:'L\'acide folique reste essentiel tout au long du premier trimestre.'),
    ],
    6: [
      ChecklistTask(id:'6-1', category:'medical',
        title:'Choisir ton médecin ou ta sage-femme',
        description:'Confirme ton choix de professionnel de santé et valide ton premier rendez-vous.'),
      ChecklistTask(id:'6-2', category:'bienetre',
        title:'Revoir ton alimentation',
        description:'Évite le poisson cru, les fromages non pasteurisés, la charcuterie et les œufs poco cuits.'),
      ChecklistTask(id:'6-3', category:'bienetre',
        title:'Commencer à bouger doucement',
        description:'La marche ou le yoga prénatal améliorent l\'humeur, la circulation et la qualité du sommeil.'),
      ChecklistTask(id:'6-4', category:'bienetre',
        title:'Prioriser le sommeil',
        description:'La fatigue est intense en ce moment. Vise 8 à 9 heures et repose-toi sans culpabilité.'),
    ],
    8: [
      ChecklistTask(id:'8-1', category:'medical',
        title:'Première consultation prénatale',
        description:'Bilan sanguin, analyse d\'urine, échographie de datation et revue des antécédents médicaux.'),
      ChecklistTask(id:'8-2', category:'medical',
        title:'Première échographie',
        description:'Confirme l\'âge gestationnel et vérifie les battements de cœur de ton bébé.'),
      ChecklistTask(id:'8-3', category:'bienetre',
        title:'Gérer les nausées matinales',
        description:'Petits repas fréquents, gingembre et vitamine B6 peuvent vraiment aider.'),
    ],
    10: [
      ChecklistTask(id:'10-1', category:'medical',
        title:'Discuter du dépistage génétique',
        description:'DPNI, clarté nucale, dépistage des porteurs — pose tes questions à ton médecin.'),
      ChecklistTask(id:'10-2', category:'pratique',
        title:'Annoncer la bonne nouvelle',
        description:'Le risque de fausse couche diminue fortement après la semaine 10 — beaucoup de familles partagent la nouvelle maintenant.'),
      ChecklistTask(id:'10-3', category:'medical',
        title:'Prendre un rendez-vous chez le dentiste',
        description:'Les hormones augmentent le risque de problèmes gingivaux. Les soins dentaires sont sûrs pendant la grossesse.'),
    ],
    12: [
      ChecklistTask(id:'12-1', category:'medical',
        title:'Dépistage du premier trimestre',
        description:'Prises de sang et échographie de la clarté nucale pour évaluer la santé chromosomique.'),
      ChecklistTask(id:'12-2', category:'pratique',
        title:'Informer ton employeur',
        description:'Consulte ta convention collective pour les droits à la maternité et commence à planifier ton absence.'),
      ChecklistTask(id:'12-3', category:'bienetre',
        title:'Commencer un journal de grossesse',
        description:'Note tes ressentis, tes symptômes et tes moments marquants — tu seras heureuse de les relire.'),
      ChecklistTask(id:'12-4', category:'bienetre',
        title:'Célébrer la fin du premier trimestre',
        description:'Ton bébé a maintenant tous ses organes. C\'est une étape extraordinaire qui mérite d\'être fêtée.'),
    ],
    16: [
      ChecklistTask(id:'16-1', category:'medical',
        title:'Test sanguin de dépistage',
        description:'Dépistage optionnel des anomalies chromosomiques — discute de l\'opportunité avec ton médecin.'),
      ChecklistTask(id:'16-2', category:'pratique',
        title:'Investir dans des vêtements de maternité',
        description:'Ton ventre va continuer à s\'arrondir — mise sur le confort et le soutien.'),
      ChecklistTask(id:'16-3', category:'bienetre',
        title:'Commencer à dormir sur le côté',
        description:'Dormir sur le côté gauche améliore la circulation sanguine vers le placenta et les reins.'),
      ChecklistTask(id:'16-4', category:'bienetre',
        title:'Parler à ton bébé',
        description:'Il commence bientôt à percevoir les sons. Ta voix est déjà sa préférée.'),
    ],
    20: [
      ChecklistTask(id:'20-1', category:'medical',
        title:'Échographie morphologique (S20)',
        description:'Examen détaillé de tous les organes, membres, position du placenta et liquide amniotique.'),
      ChecklistTask(id:'20-2', category:'pratique',
        title:'Découvrir le sexe (si tu le souhaites)',
        description:'L\'échographie morphologique peut révéler le sexe — c\'est ton choix de le savoir ou non.'),
      ChecklistTask(id:'20-3', category:'bienetre',
        title:'Continuer l\'activité physique douce',
        description:'Yoga prénatal, natation et marche sont d\'excellentes options à ce stade.'),
      ChecklistTask(id:'20-4', category:'bienetre',
        title:'Fêter le mi-parcours',
        description:'Pause bien méritée — tu es exactement à la moitié de cette aventure extraordinaire.'),
    ],
    24: [
      ChecklistTask(id:'24-1', category:'medical',
        title:'Test de tolérance au glucose',
        description:'Dépistage du diabète gestationnel. Sois à jeun 8 à 12 heures avant.'),
      ChecklistTask(id:'24-2', category:'medical',
        title:'Vérifier le taux de fer',
        description:'L\'anémie est fréquente maintenant. Aliments riches en fer et suppléments si nécessaire.'),
      ChecklistTask(id:'24-3', category:'pratique',
        title:'Commencer à aménager la chambre de bébé',
        description:'Recherche les normes de sécurité pour le lit, le type de siège auto et les essentiels.'),
      ChecklistTask(id:'24-4', category:'pratique',
        title:'S\'inscrire à une préparation à l\'accouchement',
        description:'Les cours se remplissent vite. Réserve maintenant pour les semaines 32 à 36.'),
    ],
    28: [
      ChecklistTask(id:'28-1', category:'medical',
        title:'Commencer à compter les mouvements',
        description:'Surveille les mouvements de ton bébé chaque jour — 10 mouvements en 2 heures est rassurant.'),
      ChecklistTask(id:'28-2', category:'medical',
        title:'Vaccin contre la coqueluche (Tdap)',
        description:'Protège ton bébé avant qu\'il puisse être vacciné lui-même.'),
      ChecklistTask(id:'28-3', category:'medical',
        title:'Vérification du facteur Rhésus',
        description:'Si tu es Rh négatif, une injection d\'anti-D te sera proposée maintenant.'),
      ChecklistTask(id:'28-4', category:'pratique',
        title:'Commencer la valise de maternité',
        description:'Documents, vêtements confortables, tenue pour bébé, snacks — commence la liste dès maintenant.'),
    ],
    32: [
      ChecklistTask(id:'32-1', category:'pratique',
        title:'Finaliser la valise de maternité',
        description:'Prépare-la avant la semaine 36. Inclus ta carte vitale, ta pièce d\'identité et ton plan de naissance.'),
      ChecklistTask(id:'32-2', category:'pratique',
        title:'Installer le siège auto',
        description:'Fais vérifier l\'installation — la plupart des sièges sont mal installés.'),
      ChecklistTask(id:'32-3', category:'pratique',
        title:'Rédiger ton plan de naissance',
        description:'Gestion de la douleur, personnes présentes, clampage du cordon — note tes préférences.'),
      ChecklistTask(id:'32-4', category:'bienetre',
        title:'Assister à un cours sur l\'allaitement',
        description:'Une bonne préparation améliore significativement les chances de succès et la confiance.'),
    ],
    36: [
      ChecklistTask(id:'36-1', category:'medical',
        title:'Prélèvement streptocoque B (SGB)',
        description:'Prélèvement vaginal de routine. Si positif, des antibiotiques seront administrés pendant le travail.'),
      ChecklistTask(id:'36-2', category:'pratique',
        title:'Visite de la maternité',
        description:'Repère l\'entrée, le parking et le service. Ça réduit le stress le jour J.'),
      ChecklistTask(id:'36-3', category:'pratique',
        title:'Configurer les contacts d\'urgence',
        description:'Prépare une liste claire de personnes à appeler, facilement accessible depuis ton téléphone.'),
      ChecklistTask(id:'36-4', category:'bienetre',
        title:'Préparer ton kit de confort',
        description:'Bouillotte, coussin de maternité, ballon — tout ce que tu as prévu dans ton plan de naissance.'),
    ],
    38: [
      ChecklistTask(id:'38-1', category:'medical',
        title:'Apprendre à chronométrer les contractions',
        description:'Des contractions régulières, de plus en plus intenses, à moins de 10 min d\'intervalle = appelle ton équipe.'),
      ChecklistTask(id:'38-2', category:'pratique',
        title:'Se préparer pour l\'allaitement',
        description:'Coussinets d\'allaitement, crème à la lanoline et un fauteuil confortable.'),
      ChecklistTask(id:'38-3', category:'bienetre',
        title:'Se reposer autant que possible',
        description:'Dors quand tu peux. Ton corps fait des réserves d\'énergie pour le travail.'),
    ],
    40: [
      ChecklistTask(id:'40-1', category:'medical',
        title:'Rester en contact avec ton équipe médicale',
        description:'Consulte ton médecin si tu dépasses ton terme. Tout est surveillé pour toi et ton bébé.'),
      ChecklistTask(id:'40-2', category:'bienetre',
        title:'Accepter l\'aide de ton entourage',
        description:'Laisse tes proches t\'aider pour les repas, les courses et la compagnie. Tu le mérites.'),
      ChecklistTask(id:'40-3', category:'bienetre',
        title:'Faire confiance à ton corps',
        description:'Quarante semaines d\'un travail extraordinaire. Toi et ton bébé êtes prêts pour ce moment.'),
    ],
  };
}
